Repository TeamParches/parches-chat-backend, pull requests merged in 2022-11, with the labels that each got.

#8 <feature> Estado personalizado para el usuario.
  src/database/models/User.js
  src/graphql/types/userType.js
Labels: enhancement, database, APIv1

#7 <refactor> Exportación de modulos
  src/database/index.js
  src/services/nodemailer.js
  src/utils/files.js
Labels: APIv2, refactor

#10 <feat> Multer middleware
  package-lock.json
  package.json
  src/controllers/uploadController.js
  src/routes/upload.routes.js
Labels: database, APIv1, refactor, endpoint
